# Generated by Django 2.1 on 2019-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20190616_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='sgrade',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
