# Generated by Django 2.1 on 2019-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_auto_20190616_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
