# Generated by Django 2.1 on 2019-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_auto_20190710_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
